# Generated by Django 5.2.9 on 2025-12-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('weight_kg', models.FloatField()),
                ('height_cm', models.IntegerField()),
                ('bmi', models.FloatField()),
                ('physical_activity_level', models.CharField(max_length=50)),
                ('daily_caloric_intake', models.IntegerField()),
                ('weekly_exercise_hours', models.FloatField()),
            ],
        ),
    ]
