# Generated by Django 5.2.9 on 2025-12-07 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_patient_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='bmi',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='daily_caloric_intake',
        ),
        migrations.AlterField(
            model_name='patient',
            name='physical_activity_level',
            field=models.CharField(blank=True, choices=[('Sedentary', 'Sedentary'), ('Moderate', 'Moderate'), ('Active', 'Active')], max_length=50, null=True),
        ),
    ]
