# Generated by Django 5.2.9 on 2025-12-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='calories',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='history',
            name='day',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='history',
            name='month',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='history',
            name='year',
            field=models.IntegerField(),
        ),
    ]
